### ISSUE TITLE
Target framework: .Net Framework 3.5 Client Profile

### ISSUE THREAD

**Issue by raunibl** [Syroot/KnownFolders#1]
Hi, 

can you please create a fork with the Target framework being .Net Framework 3.5 Client Profile.

Thanks in advance

**Comment by RayKoopa** [comment]
Totally possible. I hope I get to it this weekend. If you need it urgently, there should be no code-breaking changes required if you set the target framework to 3.5 manually for now.

**Comment by RayKoopa** [comment]
Support for .NET 3.5 client profile has been added with 1.0.2.0, and has been published to the NuGet repository.

**Comment by raunibl** [comment]
Thanks RyaKoopa, really appreciated.
